name: starter-kit-db

services:
  postgres:
    image: postgres:latest
    container_name: starter-kit-db
    environment:
      POSTGRES_DB: starterkit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - pg-network
    volumes:
      - pg-data:/var/lib/postgresql/data

networks:
  pg-network:

volumes:
  pg-data: